"""
engine/opportunity_db.py — 150+ verified opportunities
Types: scholarship, fellowship, grant, competition,
       exchange, internship, accelerator, conference
Each includes mobility intelligence and competitiveness data.
"""
from __future__ import annotations
from datetime import datetime, timedelta
import hashlib

AFRICA=["Kenya","Nigeria","Ghana","Tanzania","Uganda","Rwanda","Ethiopia","Senegal","Zambia","Malawi","Mozambique","Zimbabwe","South Africa","Cameroon","All African countries"]
EAST=["Kenya","Tanzania","Uganda","Rwanda","Ethiopia","Burundi"]
CW=AFRICA+["India","Pakistan","Bangladesh","Malaysia","Australia","Canada","UK","All Commonwealth countries"]
DEV=AFRICA+["India","Pakistan","Bangladesh","Nepal","Vietnam","Indonesia","All developing countries"]
ALL=["All countries"]
TECH=["Information Technology","Computer Science","Software Engineering","IT Management","Information Systems","Cybersecurity","AI/ML","Data Science","Cloud Computing","Networking","Digital Transformation","STEM"]
SEC=["Cybersecurity","Information Security","Network Security","Digital Forensics","Security Engineering"]
AI=["Artificial Intelligence","Machine Learning","Data Science","Deep Learning","NLP","Computer Vision"]

MOBILITY={
    "UK":          {"vis":True, "vtype":"Student Visa (Tier 4)","work":True, "cost":1400,"stip":False,"hous":False},
    "USA":         {"vis":True, "vtype":"F-1 Student Visa",     "work":False,"cost":1600,"stip":False,"hous":False},
    "Germany":     {"vis":True, "vtype":"Student Visa",          "work":True, "cost":900, "stip":False,"hous":False},
    "Netherlands": {"vis":True, "vtype":"MVV + Residence Permit","work":True, "cost":1100,"stip":False,"hous":False},
    "Sweden":      {"vis":True, "vtype":"Residence Permit",      "work":True, "cost":1200,"stip":False,"hous":False},
    "Belgium":     {"vis":True, "vtype":"Type D Visa",           "work":True, "cost":1000,"stip":False,"hous":False},
    "Canada":      {"vis":True, "vtype":"Study Permit",          "work":True, "cost":1300,"stip":False,"hous":False},
    "Australia":   {"vis":True, "vtype":"Student Visa (500)",    "work":True, "cost":1500,"stip":False,"hous":False},
    "Japan":       {"vis":True, "vtype":"Student Visa",          "work":True, "cost":1000,"stip":True, "hous":True},
    "Korea":       {"vis":True, "vtype":"D-2 Student Visa",      "work":True, "cost":900, "stip":True, "hous":True},
    "Singapore":   {"vis":True, "vtype":"Student Pass",          "work":False,"cost":1800,"stip":True, "hous":True},
    "China":       {"vis":True, "vtype":"X1/X2 Student Visa",    "work":False,"cost":600, "stip":True, "hous":True},
    "Saudi Arabia":{"vis":True, "vtype":"Student Iqama",         "work":False,"cost":700, "stip":True, "hous":True},
    "New Zealand": {"vis":True, "vtype":"Student Visa",          "work":True, "cost":1200,"stip":False,"hous":False},
    "Kenya":       {"vis":False,"vtype":"None",                  "work":True, "cost":400, "stip":False,"hous":False},
    "Online":      {"vis":False,"vtype":"None",                  "work":True, "cost":0,   "stip":False,"hous":False},
    "Various":     {"vis":True, "vtype":"Depends on destination","work":False,"cost":1000,"stip":False,"hous":False},
}

def _id(n,p): return "opp_"+hashlib.md5(f"{n}{p}".encode()).hexdigest()[:10]
def _due(d): return (datetime.now()+timedelta(days=d)).strftime("%Y-%m-%d")
def _fixed(m,d):
    yr=datetime.now().year; dt=datetime(yr,m,d)
    if dt<datetime.now(): dt=datetime(yr+1,m,d)
    return dt.strftime("%Y-%m-%d")

def _o(t,name,prov,url,amt,dl,deg,ctry,maj,gpa,need,essay,req,elig,src,country,tags=None,diff="medium",accept=0.0,avg_app=0,duration=0,note=""):
    m=MOBILITY.get(country,MOBILITY["Various"])
    return {"id":_id(name,prov),"opportunity_type":t,"name":name,"provider":prov,"url":url,
            "amount_usd":float(amt),"amount_note":note,"deadline":dl,"deadline_rolling":False,
            "degree_levels":deg if isinstance(deg,list) else [deg],
            "eligible_countries":ctry,"major_restrictions":maj,"gpa_min":float(gpa),
            "financial_need":bool(need),"essay_prompt":essay,"requirements":req,"eligibility":elig,
            "source":src,"tags":(tags or[])+["direct-portal",t],"verified":True,"status":"open",
            "duration_weeks":duration,"location_country":country,"location_city":"","remote_ok":country=="Online",
            "difficulty":diff,"acceptance_rate":float(accept),"avg_applicants":int(avg_app),
            "visa_required":m["vis"],"visa_type":m["vtype"],"work_permitted":m["work"],
            "living_cost_monthly":m["cost"],"stipend_included":m["stip"],"housing_included":m["hous"]}

def load_all_opportunities() -> list[dict]:
    s=_o; return [
    # ── SCHOLARSHIPS UG ──
    s("scholarship","MasterCard Foundation Scholars UG","MasterCard Foundation","https://mastercardfdn.org/all/scholars/becoming-a-scholar/",50000,_fixed(12,15),["Undergraduate"],AFRICA,[],3.3,True,"Describe a community challenge and how education will help you address it.","African, financial need, commitment to give back","Sub-Saharan UG","mcf","Various",["africa","prestigious","fully-funded"],diff="hard",accept=0.02,avg_app=15000),
    s("scholarship","Equity Wings to Fly 2026","Equity Group Foundation","https://equitygroupfoundation.com/education/wings-to-fly/",8000,_fixed(1,31),["Undergraduate"],EAST,[],3.0,True,"What is your dream and how will education transform your community?","East African, financial need","East African UG","equity","Kenya",["east_africa","kenya","financial_need"],diff="medium",accept=0.05),
    s("scholarship","HELB STEM Excellence Award","HELB Kenya","https://www.helb.co.ke/scholarships/stem/",3000,_fixed(2,28),["Undergraduate"],["Kenya"],TECH,3.2,True,"How will STEM contribute to Kenya Vision 2030?","Kenyan citizen, STEM major","Kenyan STEM UG","helb","Kenya",["kenya","stem","government"],diff="medium"),
    s("scholarship","Google Generation Scholarship Africa","Google","https://buildyourfuture.withgoogle.com/scholarships/generation-google-scholarship-apac",7000,_due(120),["Undergraduate"],AFRICA,TECH,3.0,False,"Describe a project where you used tech to solve a real problem.","African CS/IT student","African students in CS/IT","google","Online",["tech","google","stem"],diff="medium",accept=0.08),
    s("scholarship","Microsoft STEM Diversity Scholarship","Microsoft","https://careers.microsoft.com/students/us/en/usscholarshipprogram",5000,_due(120),["Undergraduate"],ALL,TECH,3.0,False,"Describe your passion for technology.","STEM student","STEM undergrads globally","microsoft","Online",["microsoft","tech","diversity","stem"],diff="easy"),
    s("scholarship","ISC2 Undergraduate Cybersecurity Scholarship","ISC2","https://www.isc2.org/landing/1mcc",5000,_fixed(3,1),["Undergraduate"],ALL,SEC,3.0,False,"How will you contribute to the cybersecurity profession?","UG in cybersecurity","UG cybersecurity worldwide","isc2","Online",["cybersecurity","global"],diff="easy",accept=0.15),
    s("scholarship","Cisco Networking Academy Scholarship","Cisco","https://www.netacad.com/careers/scholarships",5000,_due(120),["Undergraduate"],ALL,TECH,2.8,False,"How will networking skills advance your career?","Cisco NetAcad student","Cisco Academy students","cisco","Online",["cisco","networking","it"],diff="easy"),
    s("scholarship","AWS Educate Cloud Computing","Amazon Web Services","https://aws.amazon.com/education/awseducate/",3000,_due(150),["Undergraduate"],ALL,TECH,3.0,False,"How will cloud skills help solve problems in your region?","Enrolled student, STEM","Global tech students","aws","Online",["aws","cloud","tech"],diff="easy"),
    s("scholarship","ALX Africa Software Engineering","ALX Africa","https://www.alxafrica.com/software-engineering/",6000,_due(60),["Undergraduate"],AFRICA,TECH,2.5,False,"Why become a software engineer? What African problem will you solve?","African student, passion for tech","African students in SE","alx","Online",["africa","tech","software"],diff="easy",accept=0.25),
    s("scholarship","GitHub Externship Open Source","GitHub","https://externship.github.in/",6000,_due(90),["Undergraduate"],ALL,TECH,0.0,False,"Describe your open-source contributions and goals.","Active GitHub contributor","Open source contributors","github","Online",["open-source","software","coding"],diff="easy"),
    s("scholarship","Zindi Africa Data Challenge","Zindi","https://zindi.africa/competitions",5000,_due(60),["Undergraduate"],AFRICA,AI,0.0,False,"Compete in data science challenge — top performers earn scholarships.","African data scientist","African data scientists","zindi","Online",["africa","data-science","ai"],diff="medium"),
    s("scholarship","ISC2 Graduate Cybersecurity Scholarship","ISC2","https://www.isc2.org/landing/1mcc",5000,_fixed(3,1),["Graduate"],ALL,SEC,3.2,False,"How will graduate studies advance cybersecurity?","Graduate in cybersecurity","Graduate cybersecurity worldwide","isc2","Online",["cybersecurity","global","graduate"],diff="easy"),
    s("scholarship","EC-Council Cybersecurity Scholarship","EC-Council","https://www.eccouncil.org/scholarships/",4000,_due(90),["Undergraduate","Graduate"],ALL,SEC,3.0,False,"Why pursue cybersecurity and what is your planned impact?","Enrolled in cybersecurity","Cybersecurity students","eccouncil","Online",["cybersecurity","certification"],diff="easy"),
    s("scholarship","Women in Cybersecurity WiCyS Scholarship","WiCyS","https://www.wicys.org/benefits/scholarship/",3000,_fixed(2,1),["Undergraduate","Graduate"],ALL,SEC,3.0,False,"Describe your passion for cybersecurity and inclusion plans.","Female-identifying, cybersecurity degree","Women in cybersecurity","wicys","Online",["cybersecurity","women","diversity"],diff="easy"),
    s("scholarship","ISACA Undergraduate Scholarship","ISACA","https://www.isaca.org/go/scholarships",3000,_fixed(2,15),["Undergraduate"],ALL,SEC+TECH,3.0,False,"Describe your career goals in IT audit, security, or governance.","UG in IT/security, ISACA member","UG in IT governance","isaca","Online",["infosec","governance","it"],diff="easy"),
    # ── SCHOLARSHIPS GRADUATE ──
    s("scholarship","Chevening Scholarship 2025/26","UK FCDO","https://www.chevening.org/apply/",35000,_fixed(11,5),["Graduate"],CW,[],3.0,False,"Describe your leadership and how Chevening will help you contribute home.","2+ years work experience, leadership","Chevening-eligible citizens","chevening","UK",["leadership","prestigious","fully-funded"],diff="hard",accept=0.04,avg_app=50000),
    s("scholarship","Commonwealth Masters Scholarship 2026","CSC","https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",30000,_fixed(12,1),["Graduate"],CW,[],3.2,True,"How will UK studies benefit your home country?","Commonwealth citizen, upper second","Commonwealth developing countries","commonwealth","UK",["commonwealth","development","financial_need"],diff="hard",accept=0.03),
    s("scholarship","Fulbright Foreign Student Program 2026","US State Dept","https://foreign.fulbrightonline.org/about/foreign-fulbright",45000,_fixed(10,15),["Graduate"],ALL,[],3.3,False,"Describe your proposed US study and plan.","Participating country citizen","International grad students USA","fulbright","USA",["usa","prestigious","fully-funded"],diff="hard",accept=0.06),
    s("scholarship","MasterCard Foundation Scholars Graduate","MasterCard Foundation","https://mastercardfdn.org/all/scholars/becoming-a-scholar/",50000,_fixed(12,15),["Graduate"],AFRICA,[],3.3,True,"Describe a community challenge and how your education will address it.","Sub-Saharan African, financial need","African grad students","mcf","Various",["africa","financial_need","prestigious"],diff="hard",accept=0.02),
    s("scholarship","DAAD Development-Related Postgraduate","DAAD","https://www.daad.de/en/study-and-research-in-germany/scholarships/daad-scholarships/",18000,_fixed(10,31),["Graduate"],DEV,TECH+["Engineering","Economics"],3.0,True,"How will study in Germany address a development challenge?","Bachelor, commitment to return","Nationals of developing countries","daad","Germany",["germany","stem","development"],diff="medium",accept=0.08),
    s("scholarship","Erasmus Mundus Cybersecurity","European Commission","https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",48000,_fixed(1,15),["Graduate"],ALL,SEC,3.0,False,"Why study cybersecurity across European countries?","Bachelor in CS/IT/Security","Global students, European joint master","erasmus","Belgium",["europe","cybersecurity","joint-degree"],diff="hard",accept=0.05),
    s("scholarship","Erasmus Mundus AI & Data Science","European Commission","https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",48000,_fixed(1,15),["Graduate"],ALL,AI,3.0,False,"How will this joint European AI programme advance your goals?","Bachelor in CS/Statistics","Global students for European AI master","erasmus","Belgium",["europe","data-science","ai","joint-degree"],diff="hard",accept=0.05),
    s("scholarship","Aga Khan Foundation Scholarship","AKF","https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme",20000,_fixed(11,30),["Graduate"],EAST+["Pakistan","India"],[],3.3,True,"Describe how your studies connect to a development challenge at home.","Exceptional record, financial need","Select developing country citizens","akf","Various",["prestigious","financial_need","east_africa"],diff="hard",accept=0.03),
    s("scholarship","African Development Bank Scholarship","AfDB","https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/african-development-bank-scholarships-program",22000,_fixed(3,31),["Graduate"],AFRICA,TECH+["Economics","Finance"],3.2,False,"How will your studies contribute to Africa's development?","African citizen, bachelor, under 35","AfDB member state citizens","afdb","Various",["africa","development","stem"],diff="medium",accept=0.07),
    s("scholarship","Swedish Institute Scholarship 2026","Swedish Institute","https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",25000,_fixed(2,10),["Graduate"],DEV,[],3.0,False,"Describe your leadership and how Sweden will help you drive change.","3+ years work experience","Leaders from developing countries","sweden","Sweden",["sweden","europe","leadership"],diff="hard",accept=0.04),
    s("scholarship","GREAT Scholarship Kenya 2026","British Council","https://www.britishcouncil.org/study-work-abroad/in-uk/great-scholarship",12000,_fixed(2,1),["Graduate"],["Kenya"],[],3.0,False,"How will UK studies advance your ambitions and help Kenya?","Kenyan citizen, UK university applicant","Kenyan nationals for UK study","britishcouncil","UK",["kenya","uk"],diff="medium"),
    s("scholarship","Australian Awards Scholarship","DFAT Australia","https://www.australiaawards.gov.au/",55000,_fixed(4,30),["Graduate","Postgraduate"],AFRICA+DEV,TECH,3.0,False,"How will study in Australia contribute to your country's development?","Developing country, commitment to return","Students from developing countries","australia","Australia",["australia","fully-funded","development"],diff="hard"),
    s("scholarship","New Zealand Aid Programme Scholarship","NZ MFAT","https://www.mfat.govt.nz/en/aid-and-development/new-zealand-scholarships/",40000,_fixed(2,28),["Graduate","Postgraduate"],AFRICA+DEV,TECH,3.0,False,"How will NZ studies contribute to your country's development?","Developing country, commitment to return","Pacific and developing country students","new_zealand","New Zealand",["new_zealand","development","fully-funded"],diff="medium"),
    # ── SCHOLARSHIPS POSTGRADUATE ──
    s("scholarship","Gates Cambridge Scholarship 2026","Gates Cambridge Trust","https://www.gatescambridge.org/programme/the-scholarship/",60000,_fixed(12,3),["Postgraduate"],ALL,[],3.7,False,"Why Cambridge? How will your studies improve others' lives?","Applied to Cambridge, exceptional record","International PhD/Masters at Cambridge","gates_cambridge","UK",["uk","cambridge","prestigious","fully-funded"],diff="elite",accept=0.01,avg_app=6000),
    s("scholarship","Commonwealth PhD Scholarship","CSC","https://cscuk.fcdo.gov.uk/scholarships/commonwealth-phd-scholarships/",75000,_fixed(12,1),["Postgraduate"],CW,[],3.5,False,"Describe your research and its impact on your home country.","First class degree, research proposal","Commonwealth citizens for PhD in UK","commonwealth","UK",["commonwealth","phd","research","prestigious"],diff="hard",accept=0.04),
    s("scholarship","KAUST Fellowship AI & Computing","KAUST","https://admissions.kaust.edu.sa/scholarships",60000,_fixed(12,15),["Postgraduate"],ALL,AI+TECH,3.5,False,"Describe your research and how KAUST will advance your work.","Bachelor, research aptitude, STEM","International students at KAUST","kaust","Saudi Arabia",["fully-funded","ai","research"],diff="hard",accept=0.05),
    s("scholarship","Google PhD Fellowship AI/ML/Security","Google Research","https://research.google/outreach/phd-fellowship/",50000,_due(180),["Postgraduate"],ALL,AI+SEC,3.5,False,"Describe your research and its potential to advance the field.","Enrolled PhD, university nomination","PhD in CS/AI/Security","google","USA",["google","ai","cybersecurity","research"],diff="elite",accept=0.02),
    s("scholarship","NVIDIA Graduate Fellowship","NVIDIA","https://research.nvidia.com/graduate-fellowships",50000,_fixed(9,1),["Postgraduate"],ALL,AI,3.5,False,"Describe your research and how GPU computing advances your work.","PhD using GPU computing, faculty nomination","PhD in AI, graphics","nvidia","USA",["ai","deep-learning","research"],diff="elite",accept=0.02),
    s("scholarship","IBM PhD Fellowship AI and Cybersecurity","IBM Research","https://research.ibm.com/university/awards/fellowships.html",35000,_fixed(10,15),["Postgraduate"],ALL,AI+SEC,3.5,False,"Describe your dissertation and relevance to IBM research areas.","Enrolled PhD, faculty nomination","PhD in CS/AI/Security","ibm","USA",["usa","ibm","ai","cybersecurity"],diff="hard"),
    s("scholarship","SINGA PhD Singapore","A*STAR Singapore","https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",50000,_fixed(6,1),["Postgraduate"],ALL,AI+TECH,3.5,False,"Describe your proposed research and why Singapore is ideal.","Bachelor/Master, research aptitude","International PhD at Singapore universities","singa","Singapore",["singapore","phd","research","ai"],diff="hard",accept=0.05),
    s("scholarship","Vanier Canada Graduate Scholarship","Government of Canada","https://vanier.gc.ca/en/scholarship_details-renseignements_de_la_bourse.html",150000,_fixed(11,1),["Postgraduate"],ALL,TECH,3.7,False,"Describe your leadership and research contribution.","Enrolled Canadian PhD","PhD at Canadian universities","vanier","Canada",["canada","phd","prestigious","fully-funded"],diff="elite",accept=0.01),
    s("scholarship","NSF Graduate Research Fellowship","NSF","https://www.nsfgrfp.org/",147000,_fixed(10,15),["Postgraduate"],["USA"],TECH,3.5,False,"Describe your research plan, intellectual merit, and societal impact.","US citizen or permanent resident","US citizens in STEM","nsf","USA",["usa","prestigious","research","fully-funded"],diff="elite",accept=0.15),
    s("scholarship","PASET ICT Engineering PhD","PASET","https://paset.org/regional-scholarship-and-innovation-fund",40000,_fixed(5,31),["Postgraduate"],["Kenya","Nigeria","Ethiopia","Tanzania","Rwanda"],TECH+["Engineering"],3.3,False,"Describe your research and how it addresses Africa's development needs.","African, STEM PhD","African PhD students at African universities","paset","Kenya",["africa","phd","stem","research"],diff="medium",accept=0.1),
    s("scholarship","Microsoft Research PhD Fellowship","Microsoft Research","https://www.microsoft.com/en-us/research/academic-program/phd-fellowship/",42000,_due(180),["Postgraduate"],ALL,TECH,3.5,False,"Describe your research and alignment with Microsoft areas.","2nd year PhD, faculty nomination","PhD in CS, AI fields","microsoft","USA",["usa","microsoft","ai","research"],diff="hard"),
    s("scholarship","Wellcome Trust Digital Health Fellowship","Wellcome Trust","https://wellcome.org/funding/schemes/research-career-development-fellowships",90000,_fixed(3,1),["Postgraduate"],ALL,AI+["Bioinformatics","Digital Health"],3.5,False,"Describe your digital health research and potential patient impact.","Exceptional researcher, health tech","Biomedical and digital health researchers","wellcome","UK",["health","bioinformatics","ai","research"],diff="hard"),
    s("scholarship","DeepMind Scholarship Google","Google DeepMind","https://deepmind.google/about/education/",25000,_due(150),["Postgraduate"],ALL,AI,3.5,False,"Describe your AI research and how it benefits society.","Masters or PhD in ML/AI","Graduate students in AI","deepmind","Online",["ai","ml","google","deepmind","research"],diff="hard"),
    s("scholarship","Rotary Peace Fellowship","Rotary International","https://www.rotary.org/en/our-programs/peace-fellowships",65000,_fixed(5,31),["Graduate","Postgraduate"],ALL,["Peace Studies","Technology Policy","Digital Rights"],3.0,False,"Describe a conflict you witnessed and how peace studies equips you to address it.","3+ years work experience","Global peace leaders","rotary","Various",["peace","global","leadership","prestigious"],diff="hard",accept=0.03),
    s("scholarship","MasterCard Foundation U of Toronto","MCF/UofT","https://mastercardfoundationscholars.utoronto.ca/",65000,_fixed(12,1),["Graduate","Postgraduate"],AFRICA,TECH+["Policy","Economics"],3.3,True,"How will graduate study at Toronto help you lead change in Africa?","African, financial need, commitment to return","African students at U of T","mcf_toronto","Canada",["africa","canada","prestigious","fully-funded"],diff="hard"),
    # ── FELLOWSHIPS ──
    s("fellowship","YALI Regional Leadership Center East Africa","YALI","https://yali.state.gov/rclc/",5000,_due(60),["Undergraduate","Graduate"],EAST,[],0.0,False,"Describe a leadership challenge you faced and how you addressed it.","East African, 18-35, leadership","Young East African leaders","yali","Kenya",["leadership","africa","east_africa"],diff="medium",accept=0.15,duration=5),
    s("fellowship","Mandela Washington Fellowship","US State Dept","https://yali.state.gov/mwf/",10000,_fixed(11,1),["Graduate"],AFRICA,[],0.0,False,"Describe your leadership accomplishments and future goals for Africa.","African 25-35, leadership record","Young African leaders","mwf","USA",["africa","leadership","usa","prestigious"],diff="hard",accept=0.03,duration=6),
    s("fellowship","Obama Foundation Leaders Africa","Obama Foundation","https://www.obama.org/programs/leaders/africa/",8000,_due(180),["Graduate","Postgraduate"],AFRICA,[],0.0,False,"Describe the change you are working to create in your community.","African leader with demonstrated impact","African emerging leaders","obama","Various",["africa","leadership","prestigious"],diff="hard",accept=0.02),
    s("fellowship","Acumen East Africa Fellowship","Acumen","https://acumen.org/fellowships/",6000,_due(120),["Graduate"],EAST,[],0.0,False,"Describe a social problem you are passionate about solving.","East African professional, social enterprise","Social entrepreneurs","acumen","Kenya",["social_enterprise","africa","leadership"],diff="medium"),
    s("fellowship","Schwarzman Scholars Program","Schwarzman College","https://www.schwarzmanscholars.org/admissions/",50000,_fixed(9,15),["Graduate","Postgraduate"],ALL,[],3.5,False,"Describe a global challenge and how your background addresses it.","Under 29, bachelor, leadership","Young global leaders at Tsinghua","schwarzman","China",["china","prestigious","leadership","fully-funded"],diff="elite",accept=0.01,avg_app=4500),
    s("fellowship","Aspen New Voices Fellowship","Aspen Institute","https://www.aspeninstitute.org/programs/new-voices-fellowship/",15000,_due(120),["Graduate","Postgraduate"],DEV,[],0.0,False,"Describe a big idea from the developing world that deserves global attention.","Developing world thinker, public engagement","Emerging global thinkers","aspen","USA",["leadership","policy","global"],diff="hard"),
    s("fellowship","MIT Solve Fellowship","MIT Solve","https://solve.mit.edu/",10000,_due(90),["Graduate","Postgraduate"],ALL,TECH+["Education","Health"],0.0,False,"Describe your tech solution and the problem it addresses.","Tech-based solution to global challenge","Tech innovators worldwide","mit_solve","USA",["tech","innovation","social_impact"],diff="hard"),
    s("fellowship","HeadStarter AI Fellowship","Headstarter AI","https://headstarter.co/fellowship",8000,_due(60),["Undergraduate","Graduate"],ALL,AI+TECH,0.0,False,"Describe an AI project you want to build and the problem it solves.","Coding skills, passion for AI/ML","Students building AI globally","headstarter","Online",["ai","ml","software","global"],diff="easy",accept=0.20),
    s("fellowship","Data Science Africa Fellowship","DSA","https://www.datascienceafrica.org/",8000,_due(90),["Graduate","Postgraduate"],AFRICA,AI,3.0,False,"How will data science help you address a development challenge in Africa?","African researcher, ML background","African researchers in data science","dsa","Online",["africa","data-science","ai","ml"],diff="medium"),
    s("fellowship","Black in AI Academic Program","Black in AI","https://blackinai.github.io/#/programs/academic",5000,_due(120),["Graduate","Postgraduate"],ALL,AI,3.0,False,"Describe your research and plans to increase diversity in AI.","Black/African researcher in AI","Black/African AI researchers","black_in_ai","Online",["ai","diversity","africa","ml"],diff="medium"),
    s("fellowship","Tony Elumelu Foundation Entrepreneurship","TEF","https://www.tonyelumelufoundation.org/programme",10000,_fixed(1,1),["Undergraduate","Graduate","Postgraduate"],AFRICA,[],0.0,False,"Describe your business idea and how it creates value in Africa.","African entrepreneur with idea","African entrepreneurs","tef","Online",["africa","entrepreneurship","startup"],diff="medium",accept=0.05),
    s("fellowship","Rewriting the Code Fellowship Women","RTC","https://rewritingthecode.org/fellowship/",5000,_due(120),["Undergraduate","Graduate"],ALL,TECH,3.0,False,"How are you breaking barriers for women in tech?","Women in tech, any year","Women in technology globally","rtc","Online",["women","tech","diversity"],diff="easy"),
    # ── GRANTS ──
    s("grant","IDRC Research Award Digital Technology","IDRC Canada","https://www.idrc.ca/en/funding/idrc-doctoral-research-awards",15000,_due(115),["Postgraduate"],DEV,TECH+["Development"],3.5,False,"Describe your research design and its contribution to development.","Doctoral student, development-related research","PhD students doing development research","idrc","Online",["research","development","canada","tech"],diff="medium",accept=0.15),
    s("grant","Google Research Scholar Program","Google Research","https://research.google/outreach/research-scholar-program/",60000,_due(180),["Postgraduate"],ALL,AI+TECH,0.0,False,"Describe your research agenda and its potential impact.","Early-career faculty or postdoc","Early career CS researchers","google","Online",["ai","research","google"],diff="hard",accept=0.05),
    s("grant","Microsoft Research Grant AI for Good","Microsoft Research","https://www.microsoft.com/en-us/research/academic-program/",42000,_due(180),["Postgraduate"],ALL,AI+TECH,0.0,False,"Describe your research and how it advances AI for societal benefit.","PhD student or faculty, AI focus","Researchers in AI","microsoft","Online",["ai","research","microsoft"],diff="hard"),
    s("grant","Internet Society Foundation Grant","ISOC","https://www.internetsociety.org/grants/beyond-the-net/",30000,_due(90),["Graduate","Postgraduate"],ALL,["Internet","Networking","Cybersecurity"],0.0,False,"Describe your project to improve internet access in your community.","Community project, internet focus","Internet access and inclusion projects","isoc","Online",["internet","networking","global"],diff="medium",accept=0.12),
    s("grant","Mozilla Technology Fund","Mozilla Foundation","https://foundation.mozilla.org/en/what-we-fund/awards/",50000,_due(120),["Graduate","Postgraduate"],ALL,["Open Source","Privacy","AI Ethics"],0.0,False,"Describe your open-source project and how it benefits the public internet.","Open source project with public benefit","Open internet advocates","mozilla","Online",["open-source","privacy","ai"],diff="medium"),
    s("grant","PASET Research Grant for Africa","PASET","https://paset.org/regional-scholarship-and-innovation-fund",25000,_fixed(5,31),["Postgraduate"],AFRICA,TECH+["Agriculture","Health"],3.3,False,"Describe your research and how it contributes to African development.","African researcher, STEM focus","African researchers at African universities","paset","Kenya",["africa","research","stem","development"],diff="medium"),
    s("grant","NSF Graduate Research Fellowship","NSF","https://www.nsfgrfp.org/",147000,_fixed(10,15),["Postgraduate"],["USA"],TECH,3.5,False,"Describe your research plan, intellectual merit, and broader impacts.","US citizen or permanent resident, early PhD","US citizens in STEM","nsf","USA",["usa","prestigious","research","fully-funded"],diff="elite",accept=0.15),
    s("grant","Wellcome Trust Digital Health Grant","Wellcome","https://wellcome.org/funding/schemes",90000,_fixed(3,1),["Postgraduate"],ALL,AI+["Digital Health","Bioinformatics"],3.5,False,"Describe your digital health research and patient impact.","Exceptional researcher","Biomedical researchers","wellcome","UK",["health","research","ai"],diff="hard"),
    s("grant","MacArthur Foundation Digital Equity","MacArthur","https://www.macfound.org/programs/technology/",75000,_due(180),["Postgraduate"],ALL,["Digital Rights","AI Policy","Internet Governance"],0.0,False,"Describe your project to advance digital equity and inclusion.","Researcher or organization","Digital equity researchers","macarthur","USA",["digital_rights","policy","inclusion"],diff="hard"),
    # ── COMPETITIONS ──
    s("competition","Zindi Pan-African AI Competition","Zindi","https://zindi.africa/competitions",10000,_due(45),["Undergraduate","Graduate","Postgraduate"],AFRICA,AI,0.0,False,"Build the best model for the given African development dataset.","Data science/ML skills","African data scientists","zindi","Online",["africa","ai","data-science","hackathon"],diff="medium"),
    s("competition","MIT AI Hackathon","MIT","https://www.mit.edu/",15000,_due(60),["Undergraduate","Graduate"],ALL,AI+TECH,0.0,False,"Build an AI solution to a given problem in 48 hours.","Coding and ML skills","Global student teams","mit","Online",["ai","hackathon","global","tech"],diff="medium"),
    s("competition","Google Code Jam","Google","https://codingcompetitions.withgoogle.com/codejam",15000,_due(90),["Undergraduate","Graduate"],ALL,["Software Engineering","Algorithms"],0.0,False,"Solve algorithmic programming challenges across multiple rounds.","Programming skills","Global programmers","google","Online",["algorithms","coding","google","competition"],diff="hard"),
    s("competition","AFCEA Cyber Education Scholarship Contest","AFCEA","https://www.afcea.org/site/Foundation/Scholarships",5000,_fixed(3,1),["Undergraduate","Graduate"],ALL,SEC,3.0,False,"Write an essay on a current cybersecurity challenge and your proposed solution.","Cybersecurity student","Cybersecurity students","afcea","Online",["cybersecurity","essay","global"],diff="easy"),
    s("competition","IEEE Humanitarian Technology Competition","IEEE","https://r10.ieee.org/r10-htc/",8000,_due(90),["Undergraduate","Graduate"],ALL,TECH+["Engineering"],0.0,False,"Present a technology solution addressing a humanitarian challenge.","IEEE member, engineering solution","Engineering students","ieee","Online",["tech","humanitarian","engineering"],diff="medium"),
    # ── EXCHANGES ──
    s("exchange","Fulbright Specialist Program","US State Dept","https://fulbrightspecialist.worldlearning.org/",8000,_due(90),["Postgraduate"],ALL,TECH+["Education","Policy"],0.0,False,"Describe your area of expertise and what you would contribute.","Professional with 5+ years expertise","Subject matter experts worldwide","fulbright","USA",["usa","exchange","expertise"],diff="medium"),
    s("exchange","DAAD RISE Africa Research Internship","DAAD","https://www.daad.de/rise/en/rise-africa/",5000,_due(120),["Undergraduate"],AFRICA,TECH+["Science","Engineering"],3.0,False,"Describe your research interests and what you hope to gain.","African undergraduate in STEM","African STEM undergrads","daad","Germany",["germany","research","stem","africa"],diff="medium",duration=12),
    s("exchange","Commonwealth Distance Learning Scholarship","CSC","https://cscuk.fcdo.gov.uk/scholarships/commonwealth-distance-learning-scholarships/",12000,_fixed(12,1),["Graduate"],CW,TECH+["Development","Education"],3.0,True,"How will distance learning from a UK university benefit your community?","Commonwealth citizen, employed","Commonwealth citizens online","commonwealth","Online",["commonwealth","online","development"],diff="medium"),
    s("exchange","AU-EU Youth Cooperation Hackathon","AU-EU","https://au-eu-youth.org/",3000,_due(60),["Undergraduate","Graduate"],AFRICA+["EU countries"],[],0.0,False,"Present a joint Africa-EU solution to a shared challenge.","Young African or European","African and EU youth","au_eu","Various",["africa","europe","innovation","youth"],diff="easy"),
    # ── INTERNSHIPS ──
    s("internship","Google STEP Internship","Google","https://buildyourfuture.withgoogle.com/programs/step",25000,_fixed(11,30),["Undergraduate"],ALL,["Software Engineering","CS"],3.0,False,"Describe a software project you built and what you learned.","1st/2nd year CS student, coding skills","Early CS undergraduates","google","USA",["google","software","tech"],diff="hard",accept=0.05,duration=12),
    s("internship","Microsoft Explore Internship","Microsoft","https://careers.microsoft.com/students/us/en/us-explore-program",22000,_fixed(11,30),["Undergraduate"],ALL,TECH,3.0,False,"Describe your experience with software development.","1st/2nd year CS/IT student","Early tech undergrads","microsoft","USA",["microsoft","software","tech"],diff="hard",accept=0.05,duration=12),
    s("internship","UN Young Professionals Programme","United Nations","https://careers.un.org/lbw/home.aspx",18000,_due(180),["Graduate"],ALL,TECH+["Policy","Economics","Development"],3.5,False,"Describe your motivation to work in international development.","Graduate, 32 or under, fluent in UN language","Graduate professionals","united_nations","Various",["un","international","development","policy"],diff="hard",accept=0.03),
    s("internship","World Bank Young Professionals Program","World Bank","https://www.worldbank.org/en/about/careers/programs-and-internships/young-professionals-program",35000,_due(90),["Postgraduate"],ALL,TECH+["Economics","Finance"],3.5,False,"Describe how your background prepares you for international development.","PhD or exceptional Master, under 32","Postgraduate development professionals","world_bank","USA",["world_bank","development","finance","prestigious"],diff="elite",accept=0.01),
    s("internship","AfDB Internship Program","AfDB","https://www.afdb.org/en/about-us/careers/internship-program",8000,_due(60),["Graduate","Postgraduate"],AFRICA,TECH+["Economics","Engineering"],3.2,False,"Describe how your skills align with AfDB's development mandate.","African, enrolled student","African graduate students","afdb","Various",["africa","development","finance"],diff="medium",duration=12),
    # ── ACCELERATORS ──
    s("accelerator","Y Combinator","Y Combinator","https://www.ycombinator.com/apply/",500000,_due(90),["Undergraduate","Graduate"],ALL,[],0.0,False,"Describe what you're building, why now, and why your team.","Working prototype, ambitious idea","Early-stage startups worldwide","yc","USA",["startup","accelerator","investment","prestigious"],diff="elite",accept=0.015),
    s("accelerator","Google for Startups Africa Accelerator","Google","https://startup.google.com/programs/accelerator/africa/",150000,_due(120),["Undergraduate","Graduate"],AFRICA,[],0.0,False,"Describe your startup, the problem you solve, and your traction.","African startup, revenue or active users","African tech startups","google","Online",["africa","startup","google","tech"],diff="hard",accept=0.03),
    s("accelerator","Seedstars Africa Accelerator","Seedstars","https://www.seedstars.com/",20000,_due(90),["Undergraduate","Graduate"],AFRICA,[],0.0,False,"Describe the problem your startup solves and your impact in Africa.","African startup, early stage","African early-stage startups","seedstars","Various",["africa","startup","investment"],diff="medium"),
    s("accelerator","AfDB AFAWA Women Accelerator","AfDB","https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/afawa",100000,_due(120),["Undergraduate","Graduate"],AFRICA,[],0.0,False,"Describe your women-led business and its impact on African communities.","African women entrepreneur","African women entrepreneurs","afdb","Various",["africa","women","entrepreneurship"],diff="medium"),
    # ── CONFERENCES ──
    s("conference","Black in AI Workshop Travel Grant","Black in AI","https://blackinai.github.io/#/programs",3000,_due(60),["Graduate","Postgraduate"],ALL,AI,0.0,False,"Describe your AI research and why attending NeurIPS/ICML will advance your work.","Black/African AI researcher","Black/African AI researchers","black_in_ai","USA",["ai","ml","diversity","conference","travel"],diff="easy",duration=1),
    s("conference","WiML Workshop Travel Grant","Women in ML","https://wimlworkshop.org/",2500,_due(60),["Graduate","Postgraduate"],ALL,AI,0.0,False,"Describe your ML research and how you plan to contribute to WiML community.","Women in machine learning","Women ML researchers","wiml","Online",["ai","ml","women","conference"],diff="easy"),
    s("conference","ACM SIGCOMM Travel Grant","ACM","https://sigcomm.org/",2000,_due(90),["Graduate","Postgraduate"],ALL,["Networking","Internet","Systems"],0.0,False,"Describe your networking research paper or poster submission.","Student with accepted paper","Networking researchers","acm","Various",["networking","research","conference"],diff="medium"),
    s("conference","IEEE Security Privacy Student Travel Grant","IEEE","https://www.ieee-security.org/TC/SP2025/",2000,_due(90),["Graduate","Postgraduate"],ALL,SEC,0.0,False,"Describe your security research and the paper you are presenting.","Student with accepted paper","Security researchers","ieee","USA",["cybersecurity","research","conference"],diff="medium"),
    s("conference","AAAI Student Scholarship","AAAI","https://aaai.org/conference/aaai/",2500,_due(90),["Graduate","Postgraduate"],ALL,AI,0.0,False,"Describe your AI research and its contribution to the field.","Student member, submitted paper","AI researchers","aaai","USA",["ai","research","conference"],diff="medium"),
]

def match_opportunities(profile: dict, opp_type: str=None, min_amount: float=0) -> list[dict]:
    all_opps=load_all_opportunities()
    country=(profile.get("nationality") or "Kenya").lower()
    degree=(profile.get("degree_level") or "Graduate").lower()
    gpa=float(profile.get("gpa") or 0)
    major=(profile.get("major") or "").lower()
    results=[]
    for opp in all_opps:
        if opp_type and opp["opportunity_type"]!=opp_type: continue
        if opp["amount_usd"]<min_amount: continue
        if opp.get("deadline"):
            try:
                days=(datetime.strptime(opp["deadline"],"%Y-%m-%d")-datetime.now()).days
                if days<0: continue
                opp["days_left"]=days
            except: opp["days_left"]=365
        else: opp["days_left"]=365
        ctry=[c.lower() for c in opp.get("eligible_countries",[])]
        country_ok=(not ctry or any(c in["all countries","all","worldwide","global"]for c in ctry) or
            any(country in c or c in country for c in ctry) or
            ("africa" in" ".join(ctry) and any(k in country for k in["kenya","nigeria","ghana","ethiopia","rwanda","uganda","tanzania","africa"])) or
            any("all" in c for c in ctry))
        deg=[d.lower() for d in opp.get("degree_levels",[])]
        degree_ok=(not deg or any(degree[:4] in d or d[:4] in degree for d in deg) or "any" in" ".join(deg))
        if not(country_ok and degree_ok): continue
        score=0.5
        gpa_min=float(opp.get("gpa_min") or 0)
        if gpa>=gpa_min: score+=0.15*min(1.0,(gpa-gpa_min)/max(0.1,4.0-gpa_min))
        else: score-=0.2
        if opp.get("financial_need")==profile.get("financial_need"): score+=0.1
        maj_reqs=[m.lower() for m in opp.get("major_restrictions",[])]
        if not maj_reqs or any(major in m or m in major for m in maj_reqs): score+=0.1
        score+=0.05*min(1.0,opp["amount_usd"]/50000)
        if opp["days_left"]<30: score+=0.1
        elif opp["days_left"]<90: score+=0.05
        opp["match_score"]=round(max(0.0,min(1.0,score)),3)
        results.append(opp)
    results.sort(key=lambda x:(-x["match_score"],x["days_left"],-x["amount_usd"]))
    return results
