"""initial schema

Revision ID: d64d18d5ebf2
Revises: 
Create Date: 2026-05-17 23:47:45.204638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd64d18d5ebf2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pledge_logs_user_id'), table_name='pledge_logs')
    op.drop_table('pledge_logs')
    op.drop_index(op.f('ix_email_verifications_token_hash'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_user_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.alter_column('applications', 'stage',
               existing_type=postgresql.ENUM('researching', 'essay_ready', 'submitted', 'awaiting', 'won', 'rejected', name='applicationstage'),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_column('applications', 'essay_helpfulness')
    op.drop_column('applications', 'essay_used')
    op.drop_column('applications', 'feedback_text')
    op.drop_column('applications', 'feedback_submitted_at')
    op.add_column('packages', sa.Column('opportunity_type', sa.String(length=50), nullable=True))
    op.drop_column('packages', 'essay_version')
    op.drop_column('packages', 'parent_package_id')
    op.drop_column('packages', 'fields_json')
    op.drop_column('packages', 'cover_letter')
    op.alter_column('rec_requests', 'status',
               existing_type=postgresql.ENUM('requested', 'reminded', 'received', 'submitted', name='recstatus'),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.drop_column('rec_requests', 'received_at')
    op.drop_column('rec_requests', 'reminded_at')
    op.drop_column('rec_requests', 'requested_at')
    op.drop_column('rec_requests', 'briefing_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rec_requests', sa.Column('briefing_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rec_requests', sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rec_requests', sa.Column('reminded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rec_requests', sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('rec_requests', 'status',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('requested', 'reminded', 'received', 'submitted', name='recstatus'),
               existing_nullable=True)
    op.add_column('packages', sa.Column('cover_letter', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('packages', sa.Column('fields_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('packages', sa.Column('parent_package_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('packages', sa.Column('essay_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
    op.drop_column('packages', 'opportunity_type')
    op.add_column('applications', sa.Column('feedback_submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('essay_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('essay_helpfulness', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('applications', 'stage',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('researching', 'essay_ready', 'submitted', 'awaiting', 'won', 'rejected', name='applicationstage'),
               existing_nullable=True)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('email_verifications',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('email_verifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('email_verifications_pkey'))
    )
    op.create_index(op.f('ix_email_verifications_user_id'), 'email_verifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_verifications_token_hash'), 'email_verifications', ['token_hash'], unique=True)
    op.create_table('pledge_logs',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pledge_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('pledge_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pledge_logs_pkey'))
    )
    op.create_index(op.f('ix_pledge_logs_user_id'), 'pledge_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###
